apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: APP_DB_HOST
          value: db
        - name: APP_DB_NAME
          value: openloyalty
        - name: APP_DB_PASSWORD
          value: openloyalty
        - name: APP_DB_PORT
          value: "5432"
        - name: APP_DB_USER
          value: openloyalty
        - name: ELK_HOST
          value: elk
        - name: POSTGRES_DB
          value: openloyalty
        - name: POSTGRES_PASSWORD
          value: openloyalty
        - name: POSTGRES_USER
          value: openloyalty
        image: postgres:9
        imagePullPolicy: ""
        name: openloyalty-db
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: db-claim0
        persistentVolumeClaim:
          claimName: db-claim0
status: {}
