apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elk
  name: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elk
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: elk
    spec:
      containers:
      - image: divante/open-loyalty-elasticsearch:2.2.0
        imagePullPolicy: ""
        name: openloyalty-elk
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
