apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
      - env:
        - name: APP_DB_HOST
          value: db
        - name: APP_DB_NAME
          value: openloyalty
        - name: APP_DB_PASSWORD
          value: openloyalty
        - name: APP_DB_PORT
          value: "5432"
        - name: APP_DB_USER
          value: openloyalty
        - name: ELK_HOST
          value: elk
        - name: POSTGRES_DB
          value: openloyalty
        - name: POSTGRES_PASSWORD
          value: openloyalty
        - name: POSTGRES_USER
          value: openloyalty
        image: divante/open-loyalty:latest
        imagePullPolicy: ""
        name: openloyalty-backend
        resources: {}
        volumeMounts:
        - mountPath: /var/www/openloyalty/var/cache
          name: cache
        - mountPath: /var/www/openloyalty/var/logs
          name: logs
        - mountPath: /var/www/openloyalty/app/var/jwt
          name: jwt
      restartPolicy: Always
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: cache
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      - name: jwt
        persistentVolumeClaim:
          claimName: jwt
status: {}
