apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: kenlee2003
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      storage-tier: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  namespace: kenlee2003
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  selector:
    matchLabels:
      storage-tier: elasticsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: kenlee2003
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      storage-tier: cache

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: kenlee2003
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      storage-tier: logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jwt
  namespace: kenlee2003
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      storage-tier: jwt
---
